import datetime
import inspect
import json
import subprocess
from functools import lru_cache
from pathlib import Path
from typing import TYPE_CHECKING, Literal, cast

import json5
from pangloss.model_config.model_manager import ModelManager
from rich import print

if TYPE_CHECKING:
    from pangloss.model_config.models_base import (
        BaseNode,
        EdgeModel,
        MultiKeyField,
        ReifiedRelation,
        SemanticSpace,
        Trait,
    )

type AllModelTypeTypes = (
    type[BaseNode]
    | type[ReifiedRelation]
    | type[EdgeModel]
    | type[MultiKeyField]
    | type[Trait]
    | type[SemanticSpace]
)

INTERFACE_FOLDER_NAME = "interface"


def get_module_name(model: AllModelTypeTypes) -> str:
    return model.__module__.split(".")[0]


@lru_cache
def get_models(
    app_name: str | Literal["__ALL__"] = "__ALL__",
) -> list[AllModelTypeTypes]:
    return [
        model
        for model in ModelManager.all().values()
        if (app_name == "__ALL__" and get_module_name(model) != "pangloss")
        or (app_name != "__ALL__" and get_module_name(model) == app_name)
    ]


def get_module_paths(app_name: str | Literal["__ALL__"] = "__ALL__") -> set[Path]:
    """Returns paths of app_name or all app paths"""

    return set(
        [Path(inspect.getabsfile(model)).parent for model in get_models(app_name)]
    )


def get_app_path(model: AllModelTypeTypes) -> Path:
    return Path(inspect.getabsfile(model)).parent


def ensure_interface_folder(path: Path) -> None:
    """Checks whether an interface folder is present, and creates a solid-js interface library if not"""

    interface_folder_path = path.joinpath(INTERFACE_FOLDER_NAME)

    if not interface_folder_path.is_dir():
        try:
            try:
                # Creates a interface library
                initialisation_process = subprocess.Popen(
                    f'echo -e "\n\n" | bun init {INTERFACE_FOLDER_NAME}',
                    shell=True,
                    cwd=path,
                    stdout=subprocess.DEVNULL,
                )

                initialisation_process.wait()

                # Installs solid-js
                install_solid_process = subprocess.Popen(
                    "bun add solid-js --peer",
                    shell=True,
                    cwd=interface_folder_path,
                    stdout=subprocess.DEVNULL,
                )
                install_solid_process.wait()

            except Exception:
                print("Something went wrong!")

            # Make a component folder
            interface_folder_path.joinpath("components").mkdir()

            # Create a tailwindcss folder
            interface_folder_path.joinpath("app.css").write_text(
                '@import "tailwindcss";'
            )

            # Modify the tsconfig file to point "@core" to "interface_core"
            # for TS imports
            tsconfig_path = interface_folder_path.joinpath("tsconfig.json")

            tsconfig: dict = cast(dict, json5.loads(tsconfig_path.read_text()))

            core_path = (
                Path(__file__)
                .parent.parent.relative_to(tsconfig_path, walk_up=True)
                .joinpath("interface_core", "src", "*")
            )

            tsconfig["compilerOptions"]["paths"] = {"@core/*": [str(core_path)[1:]]}
            tsconfig["compilerOptions"]["baseUrl"] = "."
            tsconfig["compilerOptions"]["jsxImportSource"] = "solid-js"

            tsconfig_path.write_text(json.dumps(tsconfig, indent=4, ensure_ascii=True))

            print(f"[green bold]Created interface folder in {path}[/green bold]")
        except Exception as e:
            print("Error", e)


def build_tailwind_imports():
    sources_css_path = Path(__file__).parent.parent.joinpath(
        "interface_app", "src", ".generated", "sources.css"
    )
    with open(sources_css_path, "w") as sources_css_file_handle:
        sources_css_file_handle.write(
            f"/* AUTOGENERATED: DO NOT EDIT (Generated {datetime.datetime.now()}) */\n"
        )
        for path in get_module_paths("__ALL__"):
            components_path = path.joinpath("interface")

            if components_path.is_dir() and any(components_path.iterdir()):
                sources_css_file_handle.write(f'@source "{components_path}";\n')
